# ---------------------------------------------------------------------
# Target VM
# ---------------------------------------------------------------------
galaxy:
  host_ip: "<VM_IP_OR_HOSTNAME>"
  ssh_user: "<SSH_USER>"


# ---------------------------------------------------------------------
# Galaxy admin
# ---------------------------------------------------------------------
galaxy_admin_email: "admin@example.com"

# ---------------------------------------------------------------------
# Database secret
# ---------------------------------------------------------------------
galaxy_database_password: "CHANGE_ME_STRONG_PASSWORD"